spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: main-service-api
          uri: lb://main-service
          predicates:
            - Path=/api/**

