spring:
  application:
    name: main-service
  profiles:
    default: cloud
  config:
    import: "optional:configserver:"
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ewm}
    username: ${SPRING_DATASOURCE_USERNAME:ewm}
    password: ${SPRING_DATASOURCE_PASSWORD:ewm}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: ${EUREKA_PREFER_IP_ADDRESS:false}
    ip-address: ${HOST_IP:}
    hostname: ${HOSTNAME:localhost}

server:
  port: 0

management:
  endpoints:
    web:
      exposure:
        include: health,info

---
spring:
  config:
    activate:
      on-profile: local
  cloud:
    config:
      discovery:
        enabled: false

eureka:
  client:
    enabled: false
  instance:
    prefer-ip-address: ${EUREKA_PREFER_IP_ADDRESS:false}
    ip-address: ${HOST_IP:}
    hostname: ${HOSTNAME:localhost}

server:
  port: 8080
